@language=<%= defaultLanguage %>

###
# @name metadata
GET {{mainService}}/$metadata
Authorization: {{auth}}

###
# @name list TODO
GET {{mainService}}/TODO
Accept: application/json
Accept-Language: {{language}}
Authorization: {{auth}}
