@language=<%= defaultLanguage %>
@sapClient=<%= sapClientForDev %>

@mainService={{host}}<%= odataServicePath %>

###
# @name metadata
GET {{mainService}}/$metadata
Authorization: {{auth}}

###
# @name list TODO
GET {{mainService}}/TODO
Authorization: {{auth}}
Accept: application/json
Accept-Language: {{language}}
